/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Bloque1RouteImport } from './routes/bloque1'
import { Route as Bloque2RouteImport } from './routes/bloque2'
import { Route as Bloque3RouteImport } from './routes/bloque3'
import { Route as Bloque4RouteImport } from './routes/bloque4'
import { Route as Bloque5RouteImport } from './routes/bloque5'
import { Route as Bloque6RouteImport } from './routes/bloque6'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque1Route = Bloque1RouteImport.update({
  id: '/bloque1',
  path: '/bloque1',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque2Route = Bloque2RouteImport.update({
  id: '/bloque2',
  path: '/bloque2',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque3Route = Bloque3RouteImport.update({
  id: '/bloque3',
  path: '/bloque3',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque4Route = Bloque4RouteImport.update({
  id: '/bloque4',
  path: '/bloque4',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque5Route = Bloque5RouteImport.update({
  id: '/bloque5',
  path: '/bloque5',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque6Route = Bloque6RouteImport.update({
  id: '/bloque6',
  path: '/bloque6',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloque1': typeof Bloque1Route
  '/bloque2': typeof Bloque2Route
  '/bloque3': typeof Bloque3Route
  '/bloque4': typeof Bloque4Route
  '/bloque5': typeof Bloque5Route
  '/bloque6': typeof Bloque6Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloque1': typeof Bloque1Route
  '/bloque2': typeof Bloque2Route
  '/bloque3': typeof Bloque3Route
  '/bloque4': typeof Bloque4Route
  '/bloque5': typeof Bloque5Route
  '/bloque6': typeof Bloque6Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bloque1': typeof Bloque1Route
  '/bloque2': typeof Bloque2Route
  '/bloque3': typeof Bloque3Route
  '/bloque4': typeof Bloque4Route
  '/bloque5': typeof Bloque5Route
  '/bloque6': typeof Bloque6Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloque1'
    | '/bloque2'
    | '/bloque3'
    | '/bloque4'
    | '/bloque5'
    | '/bloque6'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bloque1'
    | '/bloque2'
    | '/bloque3'
    | '/bloque4'
    | '/bloque5'
    | '/bloque6'
  id:
    | '__root__'
    | '/'
    | '/bloque1'
    | '/bloque2'
    | '/bloque3'
    | '/bloque4'
    | '/bloque5'
    | '/bloque6'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Bloque1Route: typeof Bloque1Route
  Bloque2Route: typeof Bloque2Route
  Bloque3Route: typeof Bloque3Route
  Bloque4Route: typeof Bloque4Route
  Bloque5Route: typeof Bloque5Route
  Bloque6Route: typeof Bloque6Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque1': {
      id: '/bloque1'
      path: '/bloque1'
      fullPath: '/bloque1'
      preLoaderRoute: typeof Bloque1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque2': {
      id: '/bloque2'
      path: '/bloque2'
      fullPath: '/bloque2'
      preLoaderRoute: typeof Bloque2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque3': {
      id: '/bloque3'
      path: '/bloque3'
      fullPath: '/bloque3'
      preLoaderRoute: typeof Bloque3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque4': {
      id: '/bloque4'
      path: '/bloque4'
      fullPath: '/bloque4'
      preLoaderRoute: typeof Bloque4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque5': {
      id: '/bloque5'
      path: '/bloque5'
      fullPath: '/bloque5'
      preLoaderRoute: typeof Bloque5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque6': {
      id: '/bloque6'
      path: '/bloque6'
      fullPath: '/bloque6'
      preLoaderRoute: typeof Bloque6RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Bloque1Route: Bloque1Route,
  Bloque2Route: Bloque2Route,
  Bloque3Route: Bloque3Route,
  Bloque4Route: Bloque4Route,
  Bloque5Route: Bloque5Route,
  Bloque6Route: Bloque6Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
