/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Bloque1RouteImport } from './routes/bloque1'
import { Route as Bloque2RouteImport } from './routes/bloque2'
import { Route as Bloque3RouteImport } from './routes/bloque3'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque1Route = Bloque1RouteImport.update({
  id: '/bloque1',
  path: '/bloque1',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque2Route = Bloque2RouteImport.update({
  id: '/bloque2',
  path: '/bloque2',
  getParentRoute: () => rootRouteImport,
} as any)
const Bloque3Route = Bloque3RouteImport.update({
  id: '/bloque3',
  path: '/bloque3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloque1': typeof Bloque1Route
  '/bloque2': typeof Bloque2Route
  '/bloque3': typeof Bloque3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloque1': typeof Bloque1Route
  '/bloque2': typeof Bloque2Route
  '/bloque3': typeof Bloque3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bloque1': typeof Bloque1Route
  '/bloque2': typeof Bloque2Route
  '/bloque3': typeof Bloque3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bloque1' | '/bloque2' | '/bloque3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bloque1' | '/bloque2' | '/bloque3'
  id: '__root__' | '/' | '/bloque1' | '/bloque2' | '/bloque3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Bloque1Route: typeof Bloque1Route
  Bloque2Route: typeof Bloque2Route
  Bloque3Route: typeof Bloque3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque1': {
      id: '/bloque1'
      path: '/bloque1'
      fullPath: '/bloque1'
      preLoaderRoute: typeof Bloque1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque2': {
      id: '/bloque2'
      path: '/bloque2'
      fullPath: '/bloque2'
      preLoaderRoute: typeof Bloque2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloque3': {
      id: '/bloque3'
      path: '/bloque3'
      fullPath: '/bloque3'
      preLoaderRoute: typeof Bloque3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Bloque1Route: Bloque1Route,
  Bloque2Route: Bloque2Route,
  Bloque3Route: Bloque3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
